import { DomainCategory, ReelFormat, DifficultyLevel, ReelItem } from '../src/types';

export interface SeedReel {
  id: number;
  title: string;
  creator: string;
  avatar: string;
  format: ReelFormat;
  category: DomainCategory | 'General' | 'Entertainment' | 'Tech News';
  difficulty?: DifficultyLevel;
  content_type: 'explainer' | 'deep-dive' | 'case-study' | 'listicle' | 'meme' | 'lifestyle' | 'interview_humor' | 'news';
  description: string;
  tags: string[];
  duration_sec: number;
  thumbnail_gradient: string;
  is_curated_candidate: boolean;
  is_hype_trap?: boolean;
  views: string;
  likes: string;
  embedding_text: string;
  cloudinary_public_id?: string;
  video_url?: string;
  thumbnail_url?: string;
  duration_seconds?: number;
}

// 1. Interactive Demo Feed Reels (Featuring 5 Real Cloudinary Videos in specified order)
export const DEMO_FEED_REELS: SeedReel[] = [
  {
    id: 101,
    title: "Fast Shipping: Why moving fast beats writing perfect code 🚢⚡",
    creator: "@ship_fast_daily",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=faces",
    format: "lifestyle",
    category: "Career",
    content_type: "lifestyle",
    description: "How high-velocity software teams prioritize rapid shipping cycles, fast feedback loops, and pragmatic engineering over premature optimization.",
    tags: ["shipping", "startups", "software_engineer", "career", "productivity", "coding"],
    duration_sec: 24,
    duration_seconds: 24,
    thumbnail_gradient: "from-emerald-600 via-teal-800 to-slate-950",
    is_curated_candidate: false,
    views: "890K",
    likes: "94.5K",
    embedding_text: "Fast shipping agile iteration startup engineering culture pragmatic software delivery productivity software engineering career",
    cloudinary_public_id: "ClipDown.com_AQMCZO8zJegOCbr6TErkTSxarFeQm_qk7BtzmIaTwK4xMamz-AUOFRYo9N-r5wCn5cI65FV285XGZ59GKyKFOSLNhnKZ9sPIsO-Vsxw",
    video_url: "https://res.cloudinary.com/r9g9g9qc/video/upload/v1787030473/ClipDown.com_AQMCZO8zJegOCbr6TErkTSxarFeQm_qk7BtzmIaTwK4xMamz-AUOFRYo9N-r5wCn5cI65FV285XGZ59GKyKFOSLNhnKZ9sPIsO-Vsxw.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 102,
    title: "Interviewer: reverse a linked list. Me: 😐",
    creator: "@cs_struggles",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=faces",
    format: "interview_humor",
    category: "DSA",
    content_type: "interview_humor",
    description: "When you prepared 200 hard dynamic programming questions and they ask pointer manipulation on a whiteboard.",
    tags: ["technical_interview", "leetcode", "dsa", "cs_student", "coding_interview"],
    duration_sec: 18,
    duration_seconds: 18,
    thumbnail_gradient: "from-blue-600 via-indigo-800 to-slate-950",
    is_curated_candidate: false,
    views: "1.2M",
    likes: "142K",
    embedding_text: "Technical interview LeetCode DSA pointer manipulation reverse linked list whiteboard coding data structures",
    cloudinary_public_id: "ClipDown.com_AQOtPLOLS18iRSsxhwIvix8hDvDjU1NsFeHxvHTcKBxyt7bHTJkLe1ZyUbsHYMDSUuliT2U6_O_Vy2rkOdSXZApW",
    video_url: "https://res.cloudinary.com/r9g9g9qc/video/upload/v1787029514/ClipDown.com_AQOtPLOLS18iRSsxhwIvix8hDvDjU1NsFeHxvHTcKBxyt7bHTJkLe1ZyUbsHYMDSUuliT2U6_O_Vy2rkOdSXZApW.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 103,
    title: "Day in my life as a SWE at a high-growth startup 💻🥑",
    creator: "@startup_founder_coder",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=faces",
    format: "lifestyle",
    category: "Career",
    content_type: "lifestyle",
    description: "Morning standup, shipping microservice features to production, navigating product-market fit, and team whiteboard sessions.",
    tags: ["startup", "software_engineer", "career", "day_in_the_life", "tech_culture"],
    duration_sec: 26,
    duration_seconds: 26,
    thumbnail_gradient: "from-indigo-600 via-purple-700 to-slate-950",
    is_curated_candidate: false,
    views: "640K",
    likes: "78.3K",
    embedding_text: "Startup software engineering career day in life production deploy tech culture career progression",
    cloudinary_public_id: "ClipDown.com_AQO1Q3uWIz7TRpi96UIle2U72XbHvBUHrjsWZI_2tNILvg3TdoCvFPXx2XgK0gxAzD8_ZwK0NnuVzgynOnxd8CWR7BiyTBBoGXX6Fjs",
    video_url: "https://res.cloudinary.com/r9g9g9qc/video/upload/v1787034308/ClipDown.com_AQO1Q3uWIz7TRpi96UIle2U72XbHvBUHrjsWZI_2tNILvg3TdoCvFPXx2XgK0gxAzD8_ZwK0NnuVzgynOnxd8CWR7BiyTBBoGXX6Fjs.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 104,
    title: "static typed languages be like ☕😭",
    creator: "@dev_memes_daily",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&h=100&fit=crop&crop=faces",
    format: "meme",
    category: "Java",
    content_type: "meme",
    description: "POV: You forgot a semicolon in Java and now the compiler demands your soul. Runtime errors vs compile-time safety humor.",
    tags: ["java", "programming", "developer_humor", "compiler", "coding_meme"],
    duration_sec: 14,
    duration_seconds: 14,
    thumbnail_gradient: "from-amber-600 via-orange-700 to-stone-900",
    is_curated_candidate: false,
    views: "420K",
    likes: "38.2K",
    embedding_text: "Java compiler static typing memes programming developer humor type safety",
    cloudinary_public_id: "ClipDown.com_AQMxG-1SPznXELvbQblAR_1r1CmOMMpasF6yR72Jyajjg2n9_VAjvNpT22iSj6hlLJ6ly6xYdfm8wE8nEsPWIhUTuZn_5fH13uDH2ic",
    video_url: "https://res.cloudinary.com/r9g9g9qc/video/upload/v1787034565/ClipDown.com_AQMxG-1SPznXELvbQblAR_1r1CmOMMpasF6yR72Jyajjg2n9_VAjvNpT22iSj6hlLJ6ly6xYdfm8wE8nEsPWIhUTuZn_5fH13uDH2ic.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 105,
    title: "Cristiano Ronaldo's craziest goals in UEFA Champions League ⚽🔥",
    creator: "@goal_kings_official",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop&crop=faces",
    format: "lifestyle",
    category: "Entertainment",
    content_type: "lifestyle",
    description: "Unbelievable bicycle kick against Juventus and 40-yard screamer vs Porto in Champions League knockout stages.",
    tags: ["football", "ronaldo", "sports", "goals", "ucl", "entertainment"],
    duration_sec: 22,
    duration_seconds: 22,
    thumbnail_gradient: "from-red-600 via-amber-700 to-stone-900",
    is_curated_candidate: false,
    views: "3.4M",
    likes: "420K",
    embedding_text: "Cristiano Ronaldo football soccer goals Champions League sports highlights entertainment control item",
    cloudinary_public_id: "ClipDown.com_AQP7-yJyB0YM2m6kyRPfFGBqPnf0h9YPEyz6GWTFLvT7_W3QMbVTTVfSrmHGXS0J-iIIasgosOK-gwP7p0DIAGK_oyNyKoY1rTkX5j0",
    video_url: "https://res.cloudinary.com/r9g9g9qc/video/upload/v1787034306/ClipDown.com_AQP7-yJyB0YM2m6kyRPfFGBqPnf0h9YPEyz6GWTFLvT7_W3QMbVTTVfSrmHGXS0J-iIIasgosOK-gwP7p0DIAGK_oyNyKoY1rTkX5j0.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 106,
    title: "MacBook Pro vs ThinkPad for coding — which one?",
    creator: "@tech_rigs_hub",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=faces",
    format: "news",
    category: "Hardware",
    content_type: "explainer",
    description: "M3 Max battery life & UNIX terminal vs Linux on ThinkPad X1 Carbon keyboard travel for full-time developers.",
    tags: ["hardware", "developer_gear", "macbook", "thinkpad", "workstation"],
    duration_sec: 34,
    duration_seconds: 34,
    thumbnail_gradient: "from-slate-700 via-zinc-800 to-neutral-950",
    is_curated_candidate: false,
    views: "670K",
    likes: "51.1K",
    embedding_text: "Developer hardware MacBook Pro vs ThinkPad Linux UNIX terminal coding setup performance hardware developer setup",
    cloudinary_public_id: "ClipDown.com_AQMJFLK4kzz6asgX8Fc3NvR03e0_VorjtyCO63unm6sBsexdGIwjboOnlal-GvEu30dDo_pEBfIld-MSatXKWO6Kp-bJpBEyI_BsWdM",
    video_url: "https://res.cloudinary.com/r9g9g9qc/video/upload/v1787035100/ClipDown.com_AQMJFLK4kzz6asgX8Fc3NvR03e0_VorjtyCO63unm6sBsexdGIwjboOnlal-GvEu30dDo_pEBfIld-MSatXKWO6Kp-bJpBEyI_BsWdM.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 107,
    title: "New iPhone leak: what's changing with the camera sensor",
    creator: "@gadget_insider",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&h=100&fit=crop&crop=faces",
    format: "news",
    category: "Tech News",
    content_type: "news",
    description: "Periscope telephoto lens redesign and new capacitive capture button rumors breaking down the supply chain leaks.",
    tags: ["apple", "iphone", "tech_news", "gadgets", "camera"],
    duration_sec: 30,
    duration_seconds: 30,
    thumbnail_gradient: "from-cyan-700 via-sky-900 to-slate-950",
    is_curated_candidate: false,
    views: "810K",
    likes: "63.4K",
    embedding_text: "iPhone Apple gadget leak camera sensor consumer tech hardware news",
    cloudinary_public_id: "scrollsmart/iphone_leak",
    video_url: "https://assets.mixkit.co/videos/preview/mixkit-woman-using-her-smartphone-in-an-office-42775-large.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: 108,
    title: "Why Postgres is quietly taking over the entire backend world 🐘",
    creator: "@system_tales",
    avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&h=100&fit=crop&crop=faces",
    format: "explainer",
    category: "Cloud",
    content_type: "explainer",
    description: "From pgvector to JSONB and foreign data wrappers: why engineering teams are ditching multiple niche databases for PostgreSQL.",
    tags: ["postgres", "databases", "backend", "system_design", "cloud"],
    duration_sec: 45,
    thumbnail_gradient: "from-blue-700 via-cyan-900 to-slate-950",
    is_curated_candidate: false,
    views: "530K",
    likes: "48.2K",
    embedding_text: "PostgreSQL database pgvector backend architecture system design data storage cloud"
  },
  {
    id: 109,
    title: "Kubernetes pods explained with a fast shipping container metaphor 🚢",
    creator: "@cloud_engineer_sam",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop&crop=faces",
    format: "tutorial",
    category: "Cloud",
    content_type: "explainer",
    description: "Understand sidecar containers, localhost shared networking, and volume mounts inside a single Kubernetes Pod in 45 seconds.",
    tags: ["kubernetes", "devops", "cloud", "docker", "containers"],
    duration_sec: 42,
    thumbnail_gradient: "from-indigo-600 via-blue-900 to-slate-950",
    is_curated_candidate: false,
    views: "340K",
    likes: "29.7K",
    embedding_text: "Kubernetes pod container networking docker sidecar cloud devops infrastructure"
  }
];

// 2. Curated Recommendation Bank (36 high-value items + intentional hype bait traps)
export const CURATED_REELS_BANK: SeedReel[] = [
  // --- CAREER / SWE ---
  {
    id: 201,
    title: "What Staff Engineers actually do: Influence without authority & architecture RFCs",
    creator: "@staff_eng_chronicles",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=faces",
    format: "deep-dive",
    category: "Career",
    difficulty: "Advanced",
    content_type: "deep-dive",
    description: "The transition from Senior to Staff isn't about writing more code — it's about aligning multi-team consensus, writing impactful RFCs, and unblocking organizational bottlenecks.",
    tags: ["staff_engineer", "career_growth", "leadership", "rfc", "engineering_culture"],
    duration_sec: 58,
    thumbnail_gradient: "from-emerald-700 via-teal-900 to-stone-950",
    is_curated_candidate: true,
    views: "210K",
    likes: "24.5K",
    embedding_text: "Staff engineer career growth architecture RFC influence without authority software engineering leadership"
  },
  {
    id: 202,
    title: "Systematic debugging: How senior engineers isolate minimal reproducible bugs",
    creator: "@debug_mastery",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=faces",
    format: "explainer",
    category: "Career",
    difficulty: "Intermediate",
    content_type: "explainer",
    description: "Stop adding random print statements. Use binary search git bisect, network payload diffing, and hypothesis-driven debugging to solve elusive bugs in minutes.",
    tags: ["debugging", "best_practices", "git_bisect", "senior_engineer", "career"],
    duration_sec: 48,
    thumbnail_gradient: "from-teal-600 via-slate-800 to-neutral-950",
    is_curated_candidate: true,
    views: "340K",
    likes: "39.1K",
    embedding_text: "Debugging mindset minimal reproducible example git bisect systematic troubleshooting software engineering"
  },
  {
    id: 203,
    title: "Code Review etiquette: How to write constructive critique that teams love",
    creator: "@senior_dev_notes",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=faces",
    format: "explainer",
    category: "Career",
    difficulty: "Beginner",
    content_type: "explainer",
    description: "Separate nitpicks from architectural blockers using conventional comments (eg: 'nit:', 'blocking:', 'question:'). Build psychological safety while raising bar.",
    tags: ["code_review", "pull_requests", "teamwork", "soft_skills", "career"],
    duration_sec: 42,
    thumbnail_gradient: "from-green-600 via-emerald-800 to-slate-950",
    is_curated_candidate: true,
    views: "180K",
    likes: "19.3K",
    embedding_text: "Code review etiquette pull request constructive feedback conventional comments team culture"
  },
  {
    id: 204,
    title: "10 resume buzzwords that will instantly get you an interview at Google!",
    creator: "@hustle_coding_guru",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop&crop=faces",
    format: "listicle",
    category: "Career",
    difficulty: "Beginner",
    content_type: "listicle",
    description: "You won't believe how recruiters filter resumes! Put these 10 AI magic keywords on your resume to 10x your callback rate overnight!",
    tags: ["resume_hacks", "job_search", "buzzwords", "interview_tips"],
    duration_sec: 35,
    thumbnail_gradient: "from-rose-600 via-pink-700 to-purple-950",
    is_curated_candidate: true,
    is_hype_trap: true, // HYPE TRAP!
    views: "890K",
    likes: "12K",
    embedding_text: "10 resume buzzwords get interview hacks secrets instant callback recruiters"
  },

  // --- AI / MACHINE LEARNING ---
  {
    id: 205,
    title: "FlashAttention: How GPU SRAM caching sped up LLMs by 3x without losing precision",
    creator: "@ml_foundations",
    avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&h=100&fit=crop&crop=faces",
    format: "deep-dive",
    category: "AI",
    difficulty: "Advanced",
    content_type: "deep-dive",
    description: "Standard attention reads and writes an N x N matrix to High Bandwidth Memory (HBM). FlashAttention uses tiling in fast on-chip SRAM with online softmax calculation.",
    tags: ["machine_learning", "gpu", "flashattention", "llm", "cuda"],
    duration_sec: 59,
    thumbnail_gradient: "from-purple-600 via-violet-900 to-slate-950",
    is_curated_candidate: true,
    views: "420K",
    likes: "46.2K",
    embedding_text: "FlashAttention GPU SRAM HBM tiling online softmax LLM transformer optimization deep learning"
  },
  {
    id: 206,
    title: "Building RAG without hallucinations: Chunking strategies & reranking that actually work",
    creator: "@ai_engineer_handbook",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop&crop=faces",
    format: "explainer",
    category: "AI",
    difficulty: "Intermediate",
    content_type: "explainer",
    description: "Semantic chunking based on header hierarchies plus Cohere/BGE cross-encoder rerankers dramatically reduces hallucination in retrieval augmented generation.",
    tags: ["rag", "llm", "embeddings", "vector_search", "reranking"],
    duration_sec: 52,
    thumbnail_gradient: "from-fuchsia-600 via-purple-900 to-slate-950",
    is_curated_candidate: true,
    views: "310K",
    likes: "32.8K",
    embedding_text: "Retrieval augmented generation RAG semantic chunking cross encoder reranking vector search embeddings"
  },
  {
    id: 207,
    title: "Visualizing Self-Attention matrices: How Transformers learn relationships between tokens",
    creator: "@deeplearning_visuals",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&h=100&fit=crop&crop=faces",
    format: "explainer",
    category: "AI",
    difficulty: "Beginner",
    content_type: "explainer",
    description: "Step-by-step 3D visual explanation of Query, Key, Value dot products and how Softmax creates the attention weights connecting words.",
    tags: ["transformers", "attention_mechanism", "deep_learning", "nlp", "ai_tutorial"],
    duration_sec: 50,
    thumbnail_gradient: "from-pink-600 via-purple-800 to-slate-950",
    is_curated_candidate: true,
    views: "580K",
    likes: "61.3K",
    embedding_text: "Self-attention QKV dot product softmax transformer architecture deep learning visualization"
  },
  {
    id: 208,
    title: "Top 10 AI tools that will make you $10k/month passively while you sleep!",
    creator: "@passive_ai_millions",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&h=100&fit=crop&crop=faces",
    format: "listicle",
    category: "AI",
    difficulty: "Beginner",
    content_type: "listicle",
    description: "You won't believe tool #7! Fire your boss today with these 10 AI secrets that generate passive income with zero effort!",
    tags: ["ai_tools", "passive_income", "hacks", "get_rich"],
    duration_sec: 30,
    thumbnail_gradient: "from-amber-500 via-red-600 to-purple-950",
    is_curated_candidate: true,
    is_hype_trap: true, // HYPE TRAP!
    views: "1.5M",
    likes: "8.4K",
    embedding_text: "10 AI tools make money passive income get rich quick hacks secrets"
  },

  // --- DSA (Data Structures & Algorithms) ---
  {
    id: 209,
    title: "LRU Cache in 60s: Why combining a Doubly Linked List with a Hash Map yields O(1)",
    creator: "@dsa_in_depth",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=faces",
    format: "deep-dive",
    category: "DSA",
    difficulty: "Intermediate",
    content_type: "deep-dive",
    description: "Hash map provides O(1) key lookups, while doubly linked list provides O(1) node removal and insertion to the front/tail when capacity is exceeded.",
    tags: ["lru_cache", "data_structures", "linked_list", "hashmap", "algorithms"],
    duration_sec: 58,
    thumbnail_gradient: "from-blue-600 via-cyan-800 to-slate-950",
    is_curated_candidate: true,
    views: "490K",
    likes: "54.2K",
    embedding_text: "LRU Cache doubly linked list hash map O(1) time complexity data structures algorithms"
  },
  {
    id: 210,
    title: "Graph Traversal: The definitive guide on when to pick BFS vs DFS",
    creator: "@algo_patterns",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=faces",
    format: "explainer",
    category: "DSA",
    difficulty: "Beginner",
    content_type: "explainer",
    description: "Use Breadth-First Search with a FIFO queue for unweighted shortest paths and topological level ordering. Use Depth-First Search for cycle detection and backtracking.",
    tags: ["graphs", "bfs", "dfs", "tree_traversal", "algorithms"],
    duration_sec: 45,
    thumbnail_gradient: "from-sky-600 via-indigo-800 to-neutral-950",
    is_curated_candidate: true,
    views: "380K",
    likes: "41.9K",
    embedding_text: "Graph traversal BFS vs DFS shortest path queue recursion backtracking data structures"
  },
  {
    id: 211,
    title: "3 LeetCode tricks that will guarantee you get hired at FAANG tomorrow!",
    creator: "@algo_shortcut_king",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=faces",
    format: "listicle",
    category: "DSA",
    difficulty: "Beginner",
    content_type: "listicle",
    description: "Don't study algorithms for months! Memorize these 3 secret templates to cheat every technical interview without knowing how they work!",
    tags: ["leetcode_tricks", "interview_cheats", "faang", "hacks"],
    duration_sec: 25,
    thumbnail_gradient: "from-red-600 via-rose-700 to-purple-950",
    is_curated_candidate: true,
    is_hype_trap: true, // HYPE TRAP!
    views: "950K",
    likes: "15.1K",
    embedding_text: "3 LeetCode tricks hacks guarantee hire FAANG secret templates interview cheat"
  },

  // --- JAVA / BACKEND RUNTIMES ---
  {
    id: 212,
    title: "Java 21 Virtual Threads: How Project Loom eliminates OS thread overhead",
    creator: "@modern_java_guru",
    avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&h=100&fit=crop&crop=faces",
    format: "deep-dive",
    category: "Java",
    difficulty: "Advanced",
    content_type: "deep-dive",
    description: "Instead of 1:1 OS thread mapping (costing 1MB stack each), virtual threads are managed in user-space by the JVM, unmounting carrier threads during blocking I/O.",
    tags: ["java", "project_loom", "virtual_threads", "concurrency", "jvm"],
    duration_sec: 57,
    thumbnail_gradient: "from-amber-600 via-orange-800 to-slate-950",
    is_curated_candidate: true,
    views: "290K",
    likes: "31.2K",
    embedding_text: "Java 21 Virtual Threads Project Loom JVM concurrency carrier threads nonblocking IO performance"
  },
  {
    id: 213,
    title: "ConcurrentHashMap internals: Bucket-level synchronization & lock striping",
    creator: "@jvm_under_the_hood",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop&crop=faces",
    format: "deep-dive",
    category: "Java",
    difficulty: "Intermediate",
    content_type: "deep-dive",
    description: "How Java's ConcurrentHashMap achieves thread-safety without coarse synchronized blocks by using CAS (Compare-And-Swap) on bucket heads and TreeBins.",
    tags: ["java", "concurrenthashmap", "cas", "multithreading", "data_structures"],
    duration_sec: 53,
    thumbnail_gradient: "from-orange-600 via-amber-800 to-stone-950",
    is_curated_candidate: true,
    views: "210K",
    likes: "22.7K",
    embedding_text: "ConcurrentHashMap Java thread safety CAS lock striping synchronization JVM internal"
  },
  {
    id: 214,
    title: "Learn Java in 10 minutes: Become an enterprise developer instantly!",
    creator: "@fast_track_code",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop&crop=faces",
    format: "listicle",
    category: "Java",
    difficulty: "Beginner",
    content_type: "listicle",
    description: "You won't believe how easy Java is! Watch this 10 minute video and land a $150k enterprise developer role with no prior experience!",
    tags: ["learn_java_fast", "instant_developer", "tips", "hacks"],
    duration_sec: 20,
    thumbnail_gradient: "from-red-500 via-orange-700 to-purple-950",
    is_curated_candidate: true,
    is_hype_trap: true, // HYPE TRAP!
    views: "1.1M",
    likes: "9.2K",
    embedding_text: "Learn Java in 10 minutes instant enterprise developer hacks secrets"
  },

  // --- HLD (High-Level System Design) ---
  {
    id: 215,
    title: "How Discord scaled to 11M concurrent voice users with Elixir & Cassandra",
    creator: "@distributed_systems_lab",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&h=100&fit=crop&crop=faces",
    format: "case-study",
    category: "HLD",
    difficulty: "Advanced",
    content_type: "case-study",
    description: "Architectural breakdown of Discord's migration from MongoDB to Cassandra and finally ScyllaDB, utilizing Elixir BEAM processes for real-time state routing.",
    tags: ["system_design", "discord", "distributed_systems", "scylladb", "elixir"],
    duration_sec: 59,
    thumbnail_gradient: "from-violet-600 via-indigo-900 to-slate-950",
    is_curated_candidate: true,
    views: "640K",
    likes: "72.4K",
    embedding_text: "Discord system design architecture ScyllaDB Cassandra Elixir real time distributed systems scale"
  },
  {
    id: 216,
    title: "Rate Limiting algorithms compared: Token Bucket vs Sliding Window Log",
    creator: "@backend_architect",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&h=100&fit=crop&crop=faces",
    format: "explainer",
    category: "HLD",
    difficulty: "Intermediate",
    content_type: "explainer",
    description: "Why Token Bucket is memory efficient with burst tolerance, while Sliding Window Log with Redis ZSET provides exact boundary protection at high traffic cost.",
    tags: ["rate_limiting", "redis", "api_design", "system_design", "backend"],
    duration_sec: 49,
    thumbnail_gradient: "from-indigo-600 via-purple-900 to-slate-950",
    is_curated_candidate: true,
    views: "360K",
    likes: "41.5K",
    embedding_text: "Rate limiting algorithms token bucket sliding window log Redis API gateway system design"
  },
  {
    id: 217,
    title: "5 secret system design hacks that will fool any interview panel!",
    creator: "@system_hackz",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=faces",
    format: "listicle",
    category: "HLD",
    difficulty: "Beginner",
    content_type: "listicle",
    description: "Just say Kafka and Redis in every sentence! You won't believe how easy it is to pass high level design interviews with these 5 buzzwords.",
    tags: ["system_design_hacks", "buzzwords", "interview_tricks"],
    duration_sec: 24,
    thumbnail_gradient: "from-rose-500 via-red-700 to-purple-950",
    is_curated_candidate: true,
    is_hype_trap: true, // HYPE TRAP!
    views: "720K",
    likes: "6.1K",
    embedding_text: "5 secret system design hacks fool interview panel buzzwords Kafka Redis"
  },

  // --- CYBERSECURITY ---
  {
    id: 218,
    title: "How SQL Injection still happens inside modern ORMs when raw queries sneak in",
    creator: "@security_researcher",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=faces",
    format: "deep-dive",
    category: "Cybersecurity",
    difficulty: "Intermediate",
    content_type: "deep-dive",
    description: "Developers assume Prisma or Hibernate make them safe until someone uses string concatenation inside a raw query or order-by clause. Here is the exploit dissection.",
    tags: ["cybersecurity", "sql_injection", "appsec", "orm", "vulnerability"],
    duration_sec: 54,
    thumbnail_gradient: "from-red-700 via-rose-900 to-slate-950",
    is_curated_candidate: true,
    views: "430K",
    likes: "48.7K",
    embedding_text: "SQL injection modern ORM vulnerability raw SQL query application security exploit demonstration"
  },
  {
    id: 219,
    title: "Zero Trust Architecture: Why perimeter firewalls are completely obsolete",
    creator: "@infosec_insights",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=faces",
    format: "explainer",
    category: "Cybersecurity",
    difficulty: "Intermediate",
    content_type: "explainer",
    description: "Never trust, always verify. How mTLS, short-lived OIDC tokens, and micro-segmentation protect modern corporate infrastructures against lateral movement.",
    tags: ["zero_trust", "infosec", "mtls", "network_security", "oidc"],
    duration_sec: 46,
    thumbnail_gradient: "from-rose-600 via-slate-800 to-neutral-950",
    is_curated_candidate: true,
    views: "270K",
    likes: "29.1K",
    embedding_text: "Zero Trust architecture mTLS identity based authentication microsegmentation network security"
  },
  {
    id: 220,
    title: "Become a master hacker in 5 minutes with this free secret tool!",
    creator: "@kali_hacker_kid",
    avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&h=100&fit=crop&crop=faces",
    format: "listicle",
    category: "Cybersecurity",
    difficulty: "Beginner",
    content_type: "listicle",
    description: "Download this app and hack any Wi-Fi in 30 seconds! You won't believe what government secrets you can unlock with 1 click!",
    tags: ["hacker_tricks", "wifi_hack", "free_tools", "clickbait"],
    duration_sec: 22,
    thumbnail_gradient: "from-red-600 via-red-900 to-black",
    is_curated_candidate: true,
    is_hype_trap: true, // HYPE TRAP!
    views: "1.9M",
    likes: "14.2K",
    embedding_text: "Become master hacker 5 minutes free secret tool wifi hack clickbait"
  },

  // --- CLOUD & INFRASTRUCTURE ---
  {
    id: 221,
    title: "AWS DynamoDB single-table design: Structuring GSI partitions for sub-10ms queries",
    creator: "@cloud_architect_hq",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop&crop=faces",
    format: "deep-dive",
    category: "Cloud",
    difficulty: "Advanced",
    content_type: "deep-dive",
    description: "How to model one-to-many and many-to-many relationships in a single DynamoDB table using composite partition keys (PK/SK) and Global Secondary Indexes.",
    tags: ["aws", "dynamodb", "nosql", "single_table_design", "cloud_architecture"],
    duration_sec: 56,
    thumbnail_gradient: "from-cyan-600 via-blue-900 to-slate-950",
    is_curated_candidate: true,
    views: "350K",
    likes: "39.4K",
    embedding_text: "AWS DynamoDB single table design partition key sort key GSI NoSQL cloud database"
  },
  {
    id: 222,
    title: "Serverless cold starts: How Firecracker microVMs snapshot memory for instant boot",
    creator: "@serverless_internals",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&h=100&fit=crop&crop=faces",
    format: "explainer",
    category: "Cloud",
    difficulty: "Intermediate",
    content_type: "explainer",
    description: "Deep dive into AWS Lambda's SnapStart and Firecracker microVM architecture: taking copy-on-write memory snapshots to cut Java/Node startup latency by 90%.",
    tags: ["serverless", "aws_lambda", "firecracker", "microvms", "cold_starts"],
    duration_sec: 51,
    thumbnail_gradient: "from-sky-600 via-cyan-900 to-slate-950",
    is_curated_candidate: true,
    views: "280K",
    likes: "31.8K",
    embedding_text: "Serverless cold starts Firecracker microVM AWS Lambda SnapStart copy on write memory snapshot"
  },
  {
    id: 223,
    title: "Top 5 cloud hacks AWS engineers don't want you to know!",
    creator: "@cloud_cheat_codes",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&h=100&fit=crop&crop=faces",
    format: "listicle",
    category: "Cloud",
    difficulty: "Beginner",
    content_type: "listicle",
    description: "Get infinite free AWS credits! Amazon hates this 1 weird trick that will save you $10,000 every month on your cloud bill!",
    tags: ["aws_hacks", "free_credits", "secrets", "cloud_tricks"],
    duration_sec: 26,
    thumbnail_gradient: "from-amber-600 via-rose-700 to-purple-950",
    is_curated_candidate: true,
    is_hype_trap: true, // HYPE TRAP!
    views: "680K",
    likes: "7.8K",
    embedding_text: "Top 5 cloud hacks AWS engineers secrets free credits clickbait"
  },

  // --- HARDWARE & LOW LEVEL ---
  {
    id: 224,
    title: "CPU Branch Predictors: How your processor executes if-statements before they evaluate",
    creator: "@hardware_unlocked",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=faces",
    format: "deep-dive",
    category: "Hardware",
    difficulty: "Advanced",
    content_type: "deep-dive",
    description: "Speculative execution and 2-bit saturating counters in modern CPU pipelines: why sorting an array makes loop condition execution run 6x faster.",
    tags: ["cpu_architecture", "branch_prediction", "low_level", "c_plus_plus", "hardware"],
    duration_sec: 58,
    thumbnail_gradient: "from-zinc-600 via-slate-800 to-neutral-950",
    is_curated_candidate: true,
    views: "520K",
    likes: "61.9K",
    embedding_text: "CPU branch prediction speculative execution pipeline cache saturating counter hardware architecture"
  },
  {
    id: 225,
    title: "L1, L2, L3 Cache hierarchy: Why cache-friendly memory layouts beat fast algorithms",
    creator: "@systems_programming_pro",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=faces",
    format: "explainer",
    category: "Hardware",
    difficulty: "Intermediate",
    content_type: "explainer",
    description: "Row-major vs column-major array iteration: traversing memory sequentially triggers hardware prefetchers, avoiding devastating 100ns RAM penalty stalls.",
    tags: ["cache_lines", "memory_layout", "performance", "hardware", "latency"],
    duration_sec: 47,
    thumbnail_gradient: "from-stone-600 via-neutral-800 to-black",
    is_curated_candidate: true,
    views: "390K",
    likes: "44.1K",
    embedding_text: "CPU cache hierarchy L1 L2 L3 cache line spatial locality RAM latency memory alignment hardware"
  },
  {
    id: 226,
    title: "You won't believe what this $20 budget chip can do in 2026!",
    creator: "@tech_gadget_hype",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=faces",
    format: "listicle",
    category: "Hardware",
    difficulty: "Beginner",
    content_type: "listicle",
    description: "This secret AliExpress microprocessor is secretly better than an RTX 4090! Check out these 5 insane hacks you must try!",
    tags: ["budget_tech", "aliexpress_hacks", "chip_secrets"],
    duration_sec: 21,
    thumbnail_gradient: "from-red-600 via-amber-700 to-purple-950",
    is_curated_candidate: true,
    is_hype_trap: true, // HYPE TRAP!
    views: "1.4M",
    likes: "11.3K",
    embedding_text: "You won't believe budget chip hacks RTX killer clickbait AliExpress"
  }
];
